### ISSUE TITLE
Carthage unable to find ttf file

### ISSUE THREAD

**Issue by concertiv** [kitasuke/GoogleMaterialIconFont#16]
I believe this commit (https://github.com/kitasuke/GoogleMaterialIconFont/commit/b6baa8e3242877e67d872a6df952a3bde2029b2e) is causing this error when running `carthage update`:

```
... /Carthage/Checkouts/GoogleMaterialIconFont/Pod/Assets/GoogleMaterialIconFont.ttf: No such file or directory
A shell task failed with exit code 65:
** BUILD FAILED **
```

I presume this is due to the .ttf file being renamed to `MaterialIcons-Regular.ttf`?

**Comment by kitasuke** [comment]
This is a known issue. I'm working on this.

**Comment by sirvine** [comment]
Thanks for your work on this and the very nice PagingMenuController. (I filed this issue under my business account, and then switched to personal.)

**Comment by kitasuke** [comment]
Thanks a lot!
Please use the latest version.
