### ISSUE TITLE
Swift 2.3 compatibility (Xcode 8)

### ISSUE THREAD

**Issue by wafisher** [kitasuke/GoogleMaterialIconFont#21]
The master branch has a couple lines that need changing for Swift 2.3 compatibility. I forked it and modified my fork for anyone who wants a quick fix. If you create a new `swift2.3` branch, I'd be happy to submit a pull request.

`pod 'GoogleMaterialIconFont', :git => 'https://github.com/bowerylabs/GoogleMaterialIconFont.git'`

**Comment by kitasuke** [comment]
Thanks! It's here. https://github.com/kitasuke/GoogleMaterialIconFont/tree/swift2.3
